"use client";
// import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className={roboto.className + " h-full"}>
        <NextUIProvider>
          <div className="h-full container mx-auto overflow-y-auto overflow-x-hidden">{children}</div>
        </NextUIProvider>
      </body>
    </html>
  );
}
